require 'protobuf/rpc/service'
require 'spec/proto/test.pb'

##	!! DO NOT EDIT THIS FILE !!
## 
##	To implement this service as defined by the protobuf, simply
##	reopen Spec::Proto::TestService and implement each service method:
## 
## module Spec
## 	module Proto
## 		class TestService
## 		
## 			# request -> Spec::Proto::ResourceFindRequest
## 			# response -> Spec::Proto::Resource
## 			def find
## 				# TODO: implement find
## 			end
## 		
## 		end
## 	end
## end
##

module Spec
	module Proto
		class TestService < Protobuf::Rpc::Service
		  rpc :find, ResourceFindRequest, Resource
		end
	end
end
