### Generated by rprotoc. DO NOT EDIT!
### <proto file: test/proto/addressbook_ext.proto>
# import "test/proto/addressbook_base.proto";
# package tutorial_ext;
# 
# extend Person {
#   optional int32 age = 100;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/extend'

require 'test/proto/addressbook_base.pb'
module TutorialExt
  class Person < ::Protobuf::Message
    defined_in __FILE__
    optional :int32, :age, 100, :extension => true
  end
end