### Generated by rprotoc. DO NOT EDIT!
### <proto file: test/proto/ext_range.proto>
# message ExtRangeTest {
#   extensions 1 to 10;
# }
# 
# extend ExtRangeTest {
#   optional string a = 11;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/extend'

class ExtRangeTest < ::Protobuf::Message
  defined_in __FILE__
  extensions 1..10
end
class ExtRangeTest < ::Protobuf::Message
  defined_in __FILE__
  optional :string, :a, 11, :extension => true
end
