### Generated by rprotoc. DO NOT EDIT!
### <proto file: test/proto/merge.proto>
# package test;
# 
# message MergeMessage {
#   message InnerMessage1 {
#     required string name = 1;
#   }
#   message InnerMessage2 {
#     required string name = 1;
#     repeated InnerMessage1 repeate_message = 2;
#   }
# 
#   required string name = 1;
#   repeated InnerMessage1 repeate_message = 2;
#   required InnerMessage2 require_message = 3;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/extend'

module Test
  class MergeMessage < ::Protobuf::Message
    defined_in __FILE__
    class InnerMessage1 < ::Protobuf::Message
      defined_in __FILE__
      required :string, :name, 1
    end
    class InnerMessage2 < ::Protobuf::Message
      defined_in __FILE__
      required :string, :name, 1
      repeated :InnerMessage1, :repeate_message, 2
    end
    required :string, :name, 1
    repeated :InnerMessage1, :repeate_message, 2
    required :InnerMessage2, :require_message, 3
  end
end